# Generated by Django 3.1.4 on 2021-01-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='acc.profile')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Not Yet Shipped', 'Not Yet Shipped'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Not Yet Shipped', max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=5.99, max_digits=100)),
                ('email', models.EmailField(blank=True, help_text='enter your active email', max_length=111)),
                ('address', models.CharField(blank=True, help_text='house no.', max_length=400)),
                ('city', models.CharField(blank=True, max_length=111)),
                ('state', models.CharField(blank=True, help_text='province, country.', max_length=111)),
                ('zip_code', models.CharField(blank=True, max_length=111)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='acc.profile')),
                ('orderitems', models.ManyToManyField(related_name='orderitems', to='cart.Cart')),
            ],
        ),
    ]
