# Generated by Django 3.1.4 on 2021-01-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderitems',
        ),
        migrations.AddField(
            model_name='order',
            name='orderitems',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='cart.cart'),
        ),
    ]
