# Generated by Django 3.1.4 on 2021-01-27 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar.png', upload_to='profile/avatar/', verbose_name='Avatar')),
                ('dob', models.DateField(blank=True, help_text='fomart: 1964-12-31', null=True, verbose_name='Date Of Birth')),
                ('bio', models.TextField(verbose_name='About Me')),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(blank=True, default=10101, max_length=5)),
                ('street', models.CharField(blank=True, max_length=700, verbose_name='street address')),
                ('houseNo', models.CharField(blank=True, max_length=700, verbose_name='house number')),
                ('cell', models.CharField(max_length=12)),
                ('facebook', models.URLField(default='https://', help_text='https://web.facebook.com/kevin')),
                ('instagram', models.URLField(default='https://', help_text='https://www.instagram.com/kevin')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
