# Generated by Django 3.1.4 on 2021-01-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='houseNo',
            field=models.CharField(blank=True, max_length=700, verbose_name='house number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, max_length=700, verbose_name='street address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, help_text='fomart: 1964-12-31', null=True, verbose_name='Date Of Birth'),
        ),
    ]
