# Generated by Django 3.1.4 on 2021-01-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0002_auto_20210125_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, default=10101, max_length=5),
        ),
    ]
