# Generated by Django 3.1.4 on 2021-01-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(default='products.png', upload_to='products/thum/')),
                ('name', models.CharField(max_length=900)),
                ('info', models.TextField(verbose_name='product description')),
                ('discount', models.IntegerField(default=0.0)),
                ('price', models.IntegerField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_pub', models.BooleanField(default=False)),
            ],
        ),
    ]
