# Generated by Django 3.1.4 on 2021-01-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caover', models.ImageField(default='category.png', upload_to='category/cover/')),
                ('more', models.TextField(default=None, verbose_name='category description')),
                ('title', models.CharField(max_length=700)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(default='products.png', upload_to='products/thum/')),
                ('name', models.CharField(max_length=900)),
                ('info', models.TextField(verbose_name='product description')),
                ('location', models.CharField(default=None, max_length=10000)),
                ('price', models.IntegerField(default=0.0)),
                ('discount', models.IntegerField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_pub', models.BooleanField(default=False, verbose_name='published')),
                ('stock', models.IntegerField(default=1)),
                ('slug', models.SlugField(default=None)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='acc.profile')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category')),
                ('favourite', models.ManyToManyField(blank=True, default=None, related_name='favourite', to='acc.Profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='moreImgDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, upload_to='products/thum/', verbose_name='first image')),
                ('img2', models.ImageField(blank=True, upload_to='products/thum/', verbose_name='second image')),
                ('img3', models.ImageField(blank=True, upload_to='products/thum/', verbose_name='third image')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product')),
            ],
        ),
    ]
