# Generated by Django 3.1.4 on 2021-01-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='moreImgDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, upload_to='products/thum/')),
                ('img2', models.ImageField(blank=True, upload_to='products/thum/')),
                ('img3', models.ImageField(blank=True, upload_to='products/thum/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default=None, max_length=10000),
        ),
        migrations.AddField(
            model_name='product',
            name='more',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='more', to='products.moreimgdetails'),
        ),
    ]
