# Generated by Django 3.1.4 on 2021-01-18 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
        ('products', '0002_auto_20210118_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='acc.profile'),
        ),
    ]
