# Generated by Django 3.1.4 on 2021-01-18 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210118_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreimgdetails',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
