# Generated by Django 3.1.4 on 2021-01-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210118_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='more',
        ),
        migrations.AddField(
            model_name='moreimgdetails',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
    ]
