# Generated by Django 3.1.4 on 2021-01-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
        ('products', '0008_auto_20210118_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to='acc.Profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
