# Generated by Django 3.1.4 on 2021-01-19 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210118_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='caover',
            field=models.ImageField(default='category.png', upload_to='category/cover/'),
        ),
        migrations.AddField(
            model_name='category',
            name='more',
            field=models.TextField(default=None, verbose_name='category description'),
        ),
        migrations.AlterField(
            model_name='moreimgdetails',
            name='img1',
            field=models.ImageField(blank=True, upload_to='products/thum/', verbose_name='first image'),
        ),
        migrations.AlterField(
            model_name='moreimgdetails',
            name='img2',
            field=models.ImageField(blank=True, upload_to='products/thum/', verbose_name='second image'),
        ),
        migrations.AlterField(
            model_name='moreimgdetails',
            name='img3',
            field=models.ImageField(blank=True, upload_to='products/thum/', verbose_name='third image'),
        ),
        migrations.AlterField(
            model_name='moreimgdetails',
            name='product',
            field=models.ForeignKey(blank=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_pub',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
    ]
