# Generated by Django 3.1.4 on 2021-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_auto_20210125_1141'),
        ('products', '0012_auto_20210125_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to='acc.Profile'),
        ),
    ]
